controllers/NewsAndResourcesController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class NewsAndResourcesController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('news');
    }

    public function actionNews()
    {
        return $this->render('news');
    }

    public function actionFinancials()
    {
        return $this->render('financials');
    }
    
}

controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class NewsController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionArticle1()
    {
        return $this->render('article1');
    }

    public function actionArticle2()
    {
        return $this->render('article2');
    }
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\BecomeAVolunteerForm;
use app\models\CsvTable;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionHome()
    {
        return $this->render('home');
    }
    
    public function actionContacts()
    {
        return $this->render('contacts');
    }

    public function actionSubscribe()
    {
        if (!Yii::$app->request->isPost) {
            return 'Invalid HTTP method.';
        }

        if (!isset($_POST['email']) || empty($_POST['email'])) {
            return 'Email is required';
        }

        // Save email to the CSV table.
        $table = new CsvTable(Yii::getAlias('@runtime/subscribes.csv'));
        $table->addRecord($_POST['email'], date('Y-m-d H:i:s'));
        $table->save();

        // Send email.
        mail('golembivskyi@idhf.fund', 'You have a new subscriber at IDHF website', $_POST['email'], 'From: info@idhf.fund');

        return Yii::t('interface', 'Your email has been successfully subscribed to our newsletter!');
    }


    public function actionBecomeAVolunteer()
    {
        if (!Yii::$app->request->isPost) {
            return 'Invalid HTTP method';
        }

        $model = new BecomeAVolunteerForm();

        $model->setAttributes($_POST);
        if ($model->validate()) {
            $data = $model->attributes;
            $data []= date('Y-m-d H:i:s');

            $table = new CsvTable(Yii::getAlias('@runtime/volunteers.csv'));
            $table->addRow($data);
            $table->save();

            $data = [
                'Full name' => $model->full_name,
                'Email' => $model->full_name,
                'Phone' => $model->phone,
                'Date of birth' => $model->date_of_birth,
                'City' => $model->city,
                'Country' => $model->country,
                'Tell us' => $model->tell_us,
                'What skills' => $model->what_skills,
                'Volunteer experience' => $model->volunteer_experience,
            ];

            $body = '';
            foreach ($data as $k => $v) $body .= $k." - ".$v."\n";

            mail('golembivskyi@idhf.fund', 'The new volunteer has filled out the form at IDHF website', $body, 'From: info@idhf.fund');

            return $this->render('//get-involved/bav-success', ['model' => $model]);
        }

        return $this->redirect('/get-involved/become-a-volunteer');
    }
}

controllers/WhoWeAreController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class WhoWeAreController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('aboutIDHF');
    }

    public function actionAboutIdhf()
    {
        return $this->render('about-idhf');
    }
    
    public function actionPartners()
    {
        return $this->render('partners');
    }
    
    public function actionTeamAndBoard()
    {
        return $this->render('team-and-board');
    }
   
}

views/site/contacts.php
<?php
    use yii\helpers\Url;
    $this->title="IDHF - ".Yii::t('interface', 'Contacts');
?>

<section class="contacts-page">
    <div id="map"></div>
    <script type="text/javascript">
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 50.448755, lng: 30.374392},
                zoom: 15,
                styles: [
                            {
                                "featureType": "all",
                                "elementType": "labels",
                                "stylers": [
                                    {
                                        "visibility": "on"
                                    }
                                ]
                            },
                            {
                                "featureType": "all",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "saturation": 36
                                    },
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 40
                                    }
                                ]
                            },
                            {
                                "featureType": "all",
                                "elementType": "labels.text.stroke",
                                "stylers": [
                                    {
                                        "visibility": "on"
                                    },
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 16
                                    }
                                ]
                            },
                            {
                                "featureType": "all",
                                "elementType": "labels.icon",
                                "stylers": [
                                    {
                                        "visibility": "off"
                                    }
                                ]
                            },
                            {
                                "featureType": "administrative",
                                "elementType": "geometry.fill",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 20
                                    }
                                ]
                            },
                            {
                                "featureType": "administrative",
                                "elementType": "geometry.stroke",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 17
                                    },
                                    {
                                        "weight": 1.2
                                    }
                                ]
                            },
                            {
                                "featureType": "administrative.country",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "color": "#e5c163"
                                    }
                                ]
                            },
                            {
                                "featureType": "administrative.locality",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "color": "#c4c4c4"
                                    }
                                ]
                            },
                            {
                                "featureType": "administrative.neighborhood",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "color": "#e5c163"
                                    }
                                ]
                            },
                            {
                                "featureType": "landscape",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 20
                                    }
                                ]
                            },
                            {
                                "featureType": "poi",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 21
                                    },
                                    {
                                        "visibility": "on"
                                    }
                                ]
                            },
                            {
                                "featureType": "poi.business",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "visibility": "on"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.highway",
                                "elementType": "geometry.fill",
                                "stylers": [
                                    {
                                        "color": "#e5c163"
                                    },
                                    {
                                        "lightness": "0"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.highway",
                                "elementType": "geometry.stroke",
                                "stylers": [
                                    {
                                        "visibility": "off"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.highway",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "color": "#ffffff"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.highway",
                                "elementType": "labels.text.stroke",
                                "stylers": [
                                    {
                                        "color": "#e2b13c"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.arterial",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 18
                                    }
                                ]
                            },
                            {
                                "featureType": "road.arterial",
                                "elementType": "geometry.fill",
                                "stylers": [
                                    {
                                        "color": "#575757"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.arterial",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "color": "#ffffff"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.arterial",
                                "elementType": "labels.text.stroke",
                                "stylers": [
                                    {
                                        "color": "#2c2c2c"
                                    }
                                ]
                            },
                            {
                                "featureType": "road.local",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 16
                                    }
                                ]
                            },
                            {
                                "featureType": "road.local",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                    {
                                        "color": "#999999"
                                    }
                                ]
                            },
                            {
                                "featureType": "transit",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 19
                                    }
                                ]
                            },
                            {
                                "featureType": "water",
                                "elementType": "geometry",
                                "stylers": [
                                    {
                                        "color": "#000000"
                                    },
                                    {
                                        "lightness": 17
                                    }
                                ]
                            }
                        ]
            });

        }
    </script>
    <div class="contacts-wrap">
        <div class="cont-clmn">
            <div class="round-icon"><img src="/web/img/png/contact-info1.png" alt=""></div>
            <h3><?= Yii::t('interface', 'Our Location') ?></h3>
            <p class="contacts-text"><?= Yii::t('interface', 'L\'vivs\'ka 17, 03115 Kyiv, Ukraine') ?></p>
        </div>
        <div class="cont-clmn">
            <div class="round-icon"><img src="/web/img/png/contact-info2.png" alt=""></div>
            <h3><?= Yii::t('interface', 'Contact Us') ?></h3>
            <p class="contacts-text"><?= Yii::t('interface', 'Landline') ?>: +38 (044) 229 0753</p>
            <p class="contacts-text"><?= Yii::t('interface', 'Mobile') ?>: +38 (093) 075 7397</p>
        </div>
        <div class="cont-clmn">
            <div class="round-icon"><img src="/web/img/png/contact-info3.png" alt=""></div>
            <h3><?= Yii::t('interface', 'Write some words') ?></h3>
            <p class="contacts-text">info@idhf.fund</p>
            <p class="contacts-text">support@idhf.fund</p>
        </div>
    </div>
</section>
    
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8elwFtQUFgll7Q4Fp9x2GrmJl00bJizQ&callback=initMap" async defer></script>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/home.php
  <?php
    use yii\helpers\Url;
    $this->title="International Digital Heritage Foundation";
  ?>
   
    <section class="welcome-section">
       <div class="welcome-slide"><img class="welcome-image" src="/web/img/welcome-palace.jpg" alt="Schönbrunn Palace"></div>
       <div class="welcome-message"><span class="message-text"><?= Yii::t('interface', 'International Digital Heritage Foundation') ?></span></div>
       <div class="ornament-white">
           <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1920 148" style="enable-background:new 0 0 1920 148;" xml:space="preserve">
               <polygon class="polygon" points="960,0 860.2,19.2 860.2,38.3 1059.8,38.3 1059.8,41.3 860,41.3 860,38.3 746,38.3 746,57.5 115.2,57.5 0,139.4 0,148 1920,148 1920,136.8 1804.8,57.5 1174,57.5 1174,38.3 1060,38.3 1060,19.2 960,0 "></polygon>
           </svg>
       </div>
    </section>
    
    <section class="programms-tabs">
        <nav class="programm-menu">
            <ul class="programm-menu-ul">
                <li class="programm-item">
                    <a class="program-single-tab" href="<?=Url::to(['/what-we-do/programs/digital-cultural-ecosystem'])?>">
                        <img src="/web/img/svg/prabook.svg" class="programm-icon" alt="">
                        <span><?= Yii::t('interface', 'Prabook') ?></span>
                    </a>
                </li>
                <li class="programm-item">
                    <a class="program-single-tab" href="<?=Url::to(['/what-we-do/programs/digitizing-information'])?>">
                        <img src="/web/img/svg/digitization.svg" class="programm-icon" alt="">
                        <span><?= Yii::t('interface', 'Digitization') ?></span>
                    </a>
                </li>
                <li class="programm-item">
                    <a class="program-single-tab" href="<?=Url::to(['/what-we-do/programs/archive-activity'])?>">
                        <img src="/web/img/svg/archive.svg" class="programm-icon" alt="">
                        <span><?= Yii::t('interface', 'Archive') ?></span>
                    </a>
                </li>
                <li class="programm-item">
                    <a class="program-single-tab" href="<?=Url::to(['/what-we-do/programs/educational-activity'])?>">
                        <img src="/web/img/svg/education.svg" class="programm-icon" alt="">
                        <span><?= Yii::t('interface', 'Education') ?></span>
                    </a>
                </li>
            </ul>
        </nav>
    </section>
    
    <section class="section">
        <div class="layout-2clmn">
            <div class="left-clmn">
                <div class="design-header">
                    <div class="pre-header"><?= Yii::t('interface', 'About us') ?></div>
                    <h2><?= Yii::t('interface', 'At a glance') ?></h2>
                </div>
                <p class="gray-text"><span class="font-weight600">International Digital Heritage Foundation (IDHF)</span> – <?= Yii::t('content', 'about_idhf_p_1') ?></p>
                <p class="gray-text"><?= Yii::t('content', 'about_idhf_p_2') ?></p>
                <div class="read-more-button"><a href="<?=Url::to(['/who-we-are/about-idhf" class="read-more'])?>"><?= Yii::t('interface', 'Read More') ?></a></div>
            </div>
            <div class="right-clmn">
                <div class="img-style">
                   <div class="img-border"></div>
                   <img class="img-space" src="/web/img/welcome-1.jpg" alt="IDHF Exhibit">
                </div>
            </div>
        </div>
    </section>
    
    <section class="logotypes_section">
        <div class="logo_block_lighter">
            <a href="https://www.nlb.by/en/" target="_blank">
                <img class="logo138" src="/web/img/partners_logos/national-library-of-belarus.png" alt="National Library Of Belarus">
            </a>
        </div>
        <div class="logo_block_darker">
            <a href="http://www.ada.edu.az/" target="_blank">
                <img class="logo138" src="/web/img/partners_logos/ada-university.png" alt="ADA University">
            </a>
        </div>
        <div class="logo_block_lighter">
            <a href="https://www.nlb.by/en/" target="_blank">
                <img class="logo138" src="/web/img/partners_logos/national-library-of-belarus.png" alt="National Library Of Belarus">
            </a>
        </div>
        <div class="logo_block_darker">
            <a href="http://www.ada.edu.az/" target="_blank">
                <img class="logo138" src="/web/img/partners_logos/ada-university.png" alt="ADA University">
            </a>
        </div>
        <div class="logo_block_lighter">
            <a href="https://www.nlb.by/en/" target="_blank">
                <img class="logo138" src="/web/img/partners_logos/national-library-of-belarus.png" alt="National Library Of Belarus">
            </a>
        </div>
    </section>
    
    <section class="implemented_projects_section">
        <div class="section_content">
            <div class="section-padding"></div>
            <div class="design-header mb60">
               <div class="pre-header"><?= Yii::t('interface', 'News') ?></div>
               <h2><?= Yii::t('interface', 'Latest news') ?></h2>
            </div>
           
            <div class="single_entry">
               <div class="date">
                   <span class="fz30">05</span>
                   <span><?= Yii::t('interface', 'Jan') ?></span>
               </div>
               <div class="entry_cont">
                   <div class="entry_title"><a href="<?=Url::to(['/news/article2'])?>" class="entry_title"><?= Yii::t('news', 'The Council of European Union adopted conclusions on the Work Plan for Culture 2019-2022') ?></a></div>
                   <p class="entry_body"><?= Yii::t('news', 'a2_snipp') ?></p>
               </div>
            </div>
           
            <div class="single_entry">
               <div class="date">
                   <span class="fz30">10</span>
                   <span><?= Yii::t('interface', 'Oct') ?></span>
               </div>
               <div class="entry_cont">
                   <div class="entry_title"><a href="<?=Url::to(['/news/article1'])?>" class="entry_title"><?= Yii::t('news', 'Brazil National Museum fire') ?></a></div>
                   <p class="entry_body"><?= Yii::t('news', 'a1p1') ?></div>
            </div>
           
            <div class="read-more-button ml15_mob"><a href="<?=Url::to(['/news-and-resources/news" class="read-more'])?>" class="read-more'])?>"><?= Yii::t('interface', 'View all news') ?></a></div>
            <div class="section-padding"></div>
        </div>
    </section>
    
    <section class="gallery_homePage">
        <div class="gallery">
            <div class="gallery_block">
                <div class="gallery_pair width100">
                    <img src="/web/img/gallery_home/portfolio-1.jpg" alt="The Vatican Museum">
                    <div class="gallery_img_title">
                        <div class="gallery_img_title_head"><?= Yii::t('content', 'The Vatican Museum') ?></div>
                        <div class="gallery_img_title_body"><?= Yii::t('content', 'Sculpture') ?></div>
                    </div>
                </div>
            </div>
            <div class="gallery_block">
                <div class="gallery_pair width50">
                    <img src="/web/img/gallery_home/portfolio-2.jpg" alt="The Vatican Museum">
                    <div class="gallery_img_title">
                        <div class="gallery_img_title_head"><?= Yii::t('content', 'The Vatican Museum') ?></div>
                        <div class="gallery_img_title_body"><?= Yii::t('content', 'Architecture') ?></div>
                    </div>
                </div>
                <div class="gallery_pair width50">
                    <img src="/web/img/gallery_home/portfolio-3.jpg" alt="Modern Art Museum">
                    <div class="gallery_img_title">
                        <div class="gallery_img_title_head"><?= Yii::t('content', 'Modern Art Museum') ?></div>
                        <div class="gallery_img_title_body"><?= Yii::t('content', 'Sculpture') ?></div>
                    </div>
                </div>
            </div>
            
            
            <div class="gallery_block">
                <div class="gallery_pair width50">
                    <img src="/web/img/gallery_home/portfolio-4.jpg" alt="The British Museum">
                    <div class="gallery_img_title">
                        <div class="gallery_img_title_head"><?= Yii::t('content', 'The British Museum') ?></div>
                        <div class="gallery_img_title_body"><?= Yii::t('content', 'Architecture') ?></div>
                    </div>
                </div>
                <div class="gallery_pair width50">
                    <img src="/web/img/gallery_home/portfolio-5.jpg" alt="The Pushkin Museum">
                    <div class="gallery_img_title">
                        <div class="gallery_img_title_head"><?= Yii::t('content', 'The Pushkin Museum') ?></div>
                        <div class="gallery_img_title_body"><?= Yii::t('content', 'Sculpture') ?></div>
                    </div>
                </div>
            </div>
            <div class="gallery_block">
                <div class="gallery_pair width100">
                    <img src="/web/img/gallery_home/portfolio-6.jpg" alt="The Vatican Museum">
                    <div class="gallery_img_title">
                        <div class="gallery_img_title_head"><?= Yii::t('content', 'The Vatican Museum') ?></div>
                        <div class="gallery_img_title_body"><?= Yii::t('content', 'Sculpture') ?></div>
                    </div>
                </div>
            </div>
            

        </div>
    </section>